name: Securty

on:
  push:
    branches: '**'

permissions:
  contents: write

jobs:
  sec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Security Dependencies
        run: |
          make sec-dependencies
      - name: Scan Crate
        run: |
          make sec
